title: "Evaluating Federal Tax Credit Programs"
subtitle: "CPP 528 Fall 2021 Group 5 "
author: "Amy T. Trumpower, Melissa Millican, Sean Harrington, Joseph Papcznskir"
description: "An Examination of Federal Tax Programs on Median Home Value"


# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: false         # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: true             # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: true          # radically minimalistic theme

navigation:                  # show navigation links in the header	
  - index.html
  - https://r-class.github.io/cpp-528-fall-2021-group-05/ch01-execsum/
  - about.md
  - license.md
  


icons:                       
# show icons in the header, for all possible icons see http://fontawesome.io/icons/
# envelope: "mailto:niklasbuschmann@users.noreply.github.com"
github: "https://github.com/R-Class/cpp-528-fall-2021-group-05/tree/main"
 
  
 
  
comments:                    # embed disqus or isso comments
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"



plugins: 
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout

remote_theme: pages-themes/minimal@v0.2.0


