---
title: "Lab 05 - Predicting MHV Change"
subtitle: "CPP528 Group 05 Fall 2021"
author: "Cristian E. Nuno updated by: Amy T. Trumpower, Melissa Millican, Sean Harrington, Joseph Papcznski"
updated by: "Amy T. Trumpower, Melissa Millican, Sean Harrington, Joseph Papcznski"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    df_print: paged
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
# define chunk options
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load the necessary packages ----
library(dplyr)
library(import)
library(tidyverse)
library(here)
library(knitr)
library(pander)
library(stargazer)
library(scales)
library(rmarkdown)
library(namespace)
#set randomization seed ---
set.seed(1234)
#Load necessary functions and objects ---
#note:  all of these are R objects that will be used throughout this .rmd file
import::here("S_TYPE",
             "d",
             "df",
             "d3",
             "PLOTS",
             " %>% ",
             .from = here::here("~/CPP528/cpp-528-fall-2021-group-05/labs/wk05/lab_05_source.R"),
             .character_only = TRUE)
detach("package:import", unload = TRUE)
```


```{r}
d <- readRDS(file = "~/CPP528/cpp-528-fall-2021-group-05/data/rodeo/rodeo-data-cs.rds")
```


```{r}
y1 <- log( d$mhv.00 )
y2 <- log( d$mhv.10 )

# create a variable that identifies if a tract received NMTC funding
treat <- as.numeric( d$num.nmtc > 0 )
income <- log(d$hinc00)
poverty <- log(d$pov.rate.00)
unemp <- log(d$p.unemp.00)

#change variable name so we don't copy
treat.lihtc <- as.numeric(d$num.lihtc >0)

# store the year 2000 data
d1 <- data.frame( y=y1, treat=treat, post=0, unemp, income, poverty)
# store the year 2010 data
d2 <- data.frame( y=y2, treat=treat, post=1, unemp, income, poverty)

# stack the two time periods together
d3 <- rbind( d1, d2 )



# store the year 2000 data
e1 <- data.frame( y=y1, treat=treat.lihtc, post=0, unemp, income, poverty)
# store the year 2010 data
e2 <- data.frame( y=y2, treat=treat.lihtc, post=1, unemp, income, poverty )

# stack the two time periods together
e3 <- rbind( e1, e2 )
```


```{r}
# create the difference in difference model
# note: treat = B1, post = B2, treat*post = B3
nmtc <- lm( y ~ treat + post + treat*post + income + poverty + unemp, data=d3 )

lihtc <- lm( y ~ treat + post + treat*post + income + poverty + unemp, data=e3 )

# display model results
stargazer::stargazer(nmtc, lihtc,
                     type = "text",
                     digits = 2, column.labes = c("NMTC", "LIHTC"), covariate.lables = c("intercept (b0)", "treat(b1)", "post(b2)", "Income", "Poverty", "Unemployment", "treat x post (b3)"), digits = 2, intercept.bottom = FALSE)
```

